use hospital;
select * from appointment ;



# List all appointments with patient and doctor full names
SELECT 
    a.appointment_id,
    CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
    CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
    a.appointment_date,
    a.status
FROM appointment a
JOIN patient p ON a.patient_id = p.patient_id
JOIN doctor d ON a.doctor_id = d.doctor_id;



#Total appointments for each doctor
SELECT 
    CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
    COUNT(a.appointment_id) AS total_appointments
FROM doctor d
JOIN appointment a ON d.doctor_id = a.doctor_id
GROUP BY doctor_name
ORDER BY total_appointments DESC;




# Revenue generated by each doctor
SELECT 
    CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
    SUM(b.amount) AS total_revenue
FROM doctor d
JOIN appointment a ON d.doctor_id = a.doctor_id
JOIN treatment t ON a.appointment_id = t.appointment_id
JOIN billing b ON t.treatment_id = b.treatment_id
GROUP BY doctor_name
ORDER BY total_revenue DESC;




#Top 5 patients by total billing
SELECT 
    CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
    SUM(b.amount) AS total_billed
FROM patient p
JOIN appointment a ON p.patient_id = a.patient_id
JOIN treatment t ON a.appointment_id = t.appointment_id
JOIN billing b ON t.treatment_id = b.treatment_id
GROUP BY patient_name
ORDER BY total_billed DESC
LIMIT 5;





#Patients with unpaid bills
SELECT DISTINCT 
    CONCAT(p.first_name, ' ', p.last_name) AS patient_name
FROM patient p
JOIN appointment a ON p.patient_id = a.patient_id
JOIN treatment t ON a.appointment_id = t.appointment_id
JOIN billing b ON t.treatment_id = b.treatment_id
WHERE b.payment_status = 'Unpaid';




#Most common top 5 diagnosis
SELECT 
    t.diagnosis,
    COUNT(*) AS count
FROM treatment t
GROUP BY t.diagnosis
ORDER BY count DESC
LIMIT 5;






#Billing history for each patient
SELECT 
    CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
    b.amount,
    b.billing_date,
    b.payment_status
FROM patient p
JOIN appointment a ON p.patient_id = a.patient_id
JOIN treatment t ON a.appointment_id = t.appointment_id
JOIN billing b ON t.treatment_id = b.treatment_id;





#Average billing per treatment type
SELECT 
    t.treatment_details,
    AVG(b.amount) AS avg_amount
FROM treatment t
JOIN billing b ON t.treatment_id = b.treatment_id
GROUP BY t.treatment_details;




#Patients with more than one appointment
SELECT 
    CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
    COUNT(a.appointment_id) AS total_appointments
FROM patient p
JOIN appointment a ON p.patient_id = a.patient_id
GROUP BY patient_name
HAVING total_appointments > 1;







#Monthly revenue trend
SELECT 
    DATE_FORMAT(b.billing_date, '%Y-%m') AS billing_month,
    SUM(b.amount) AS total_revenue
FROM billing b
GROUP BY billing_month
ORDER BY billing_month;


